"""init schemas

Revision ID: 3784f45478bd
Revises: 
Create Date: 2026-06-10 00:01:21.982986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3784f45478bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aesculap',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('eng_desc', sa.String(length=1024), nullable=False),
    sa.Column('viet_desc', sa.String(length=1024), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('alternative_code', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=False, default='B-Braun'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_aesculap_brand'), 'aesculap', ['brand'], unique=False)
    op.create_index(op.f('ix_aesculap_code'), 'aesculap', ['code'], unique=False)
    op.create_table('kls_martin',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('eng_desc', sa.String(length=1024), nullable=False),
    sa.Column('viet_desc', sa.String(length=1024), nullable=False),
    sa.Column('alternative_code', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=False, default='Martin'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_kls_martin_brand'), 'kls_martin', ['brand'], unique=False)
    op.create_index(op.f('ix_kls_martin_code'), 'kls_martin', ['code'], unique=False)
    op.create_table('martin_images',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('img1_url', sa.String(length=50), nullable=False),
    sa.Column('img2_url', sa.String(length=50), nullable=True),
    sa.Column('img3_url', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_martin_images_code'), 'martin_images', ['code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_martin_images_code'), table_name='martin_images')
    op.drop_table('martin_images')
    op.drop_index(op.f('ix_kls_martin_code'), table_name='kls_martin')
    op.drop_index(op.f('ix_kls_martin_brand'), table_name='kls_martin')
    op.drop_table('kls_martin')
    op.drop_index(op.f('ix_aesculap_code'), table_name='aesculap')
    op.drop_index(op.f('ix_aesculap_brand'), table_name='aesculap')
    op.drop_table('aesculap')
    # ### end Alembic commands ###
