"""change brand to nullable

Revision ID: 3bf6263a5a22
Revises: 3784f45478bd
Create Date: 2026-06-10 00:09:28.234330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf6263a5a22'
down_revision: Union[str, Sequence[str], None] = '3784f45478bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aesculap', 'brand',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('kls_martin', 'brand',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kls_martin', 'brand',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('aesculap', 'brand',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
