"""update images column character count

Revision ID: ccb68d2c32a4
Revises: 3bf6263a5a22
Create Date: 2026-06-10 00:11:59.875517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb68d2c32a4'
down_revision: Union[str, Sequence[str], None] = '3bf6263a5a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aesculap', 'image',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('martin_images', 'img1_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('martin_images', 'img2_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('martin_images', 'img3_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('martin_images', 'img3_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('martin_images', 'img2_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('martin_images', 'img1_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('aesculap', 'image',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
