"""changed table column names.

Revision ID: d19752559017
Revises: 1d26d9f6e97c
Create Date: 2026-06-12 05:21:49.851202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19752559017'
down_revision: Union[str, Sequence[str], None] = '1d26d9f6e97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aesculap', sa.Column('alternative', sa.String(length=20), nullable=True))
    op.drop_column('aesculap', 'alternative')
    op.add_column('kls_martin', sa.Column('eng', sa.String(length=1024), nullable=False))
    op.add_column('kls_martin', sa.Column('viet', sa.String(length=1024), nullable=False))
    op.add_column('kls_martin', sa.Column('alternative', sa.String(length=20), nullable=True))
    op.drop_column('kls_martin', 'alternative')
    op.drop_column('kls_martin', 'viet')
    op.drop_column('kls_martin', 'eng')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kls_martin', sa.Column('eng', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('kls_martin', sa.Column('viet', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('kls_martin', sa.Column('alternative', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('kls_martin', 'alternative')
    op.drop_column('kls_martin', 'viet')
    op.drop_column('kls_martin', 'eng')
    op.add_column('aesculap', sa.Column('alternative', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('aesculap', 'alternative')
    # ### end Alembic commands ###
