-- Active: 1776482529452@@localhost@5432@calohub
-- Generated by the database client.
CREATE TABLE if NOT EXISTS aesculap(
    code varchar(20) PRIMARY KEY,
    eng_desc varchar(255) NOT NULL,
    viet_desc varchar(255) NOT NULL,
    image varchar(255),
    alternative_code varchar(20),
    brand varchar(20) DEFAULT 'Aesculap'
);

-- Generated by the database client.
CREATE TABLE if NOT EXISTS kls_martin(
    code varchar(20) PRIMARY KEY,
    eng_desc varchar(255) NOT NULL,
    viet_desc varchar(255) NOT NULL,
    brand varchar(20) DEFAULT 'Martin'
);

-- Generated by the database client.
CREATE TABLE if NOT EXISTS martin_images(
    code varchar(20) PRIMARY KEY,
    img1_url TEXT NOT NULL,
    img2_url TEXT,
    img3_url TEXT,
    CONSTRAINT fk_code FOREIGN key(code) REFERENCES kls_martin(code) ON DELETE CASCADE
);