-- +goose Up
CREATE TABLE products (
    code        VARCHAR(20) PRIMARY KEY,
    eng         VARCHAR(1024) NOT NULL,
    viet        VARCHAR(1024) NOT NULL,
    alternative VARCHAR(20) NOT NULL DEFAULT '',
    brand       VARCHAR(20) NOT NULL
);

CREATE TABLE images (
    code   VARCHAR(20) PRIMARY KEY REFERENCES products(code) ON DELETE CASCADE,
    images TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE martin_report_list (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE martin_report_products (
    report_id INT NOT NULL REFERENCES martin_report_list(id) ON DELETE CASCADE,
    row_no    INT NOT NULL,
    code      VARCHAR(20) NOT NULL REFERENCES products(code) ON DELETE CASCADE,
    eng       VARCHAR(1024) NOT NULL,
    image     TEXT,
    quantity  INT NOT NULL DEFAULT 0,
    PRIMARY KEY (report_id, row_no)
);

CREATE INDEX idx_martin_report_products_code ON martin_report_products(code);

-- +goose Down
DROP TABLE IF EXISTS martin_report_products;
DROP TABLE IF EXISTS martin_report_list;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS products;